name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git Bot Identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy using Angular CLI
        run: npx ng deploy --base-href=/devops-td3-angular-pipeline/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
